### ISSUE TITLE
Feature: Add ability to use the uuid type for some of the id types (rather than text)

### ISSUE THREAD

**Issue by dlight** [VADOSWARE/pg_idkit#11]
# Context

Per [this discussion](https://news.ycombinator.com/item?id=32805325), this extension uses `  text`   rather than `  uuid`   for ulid and other identifiers with the same size of uuid. It appears this would introduce some size overhead.

# Proposal

I think that ulid, uuidv6, uuidv7, etc. should use the `  uuid`   postgres type.

# Alternatives

Keep it as is? It appears one can generate as text and then convert to uuid later.

**Comment by t3hmrman** [comment]
Hey @dlight agreed -- adding `_uuid` functions (and maybe shifting the naming scheme somewhat or adding one that is easier to guess/predict that produces `text`vs `uuid` is something that should be done.
