### ISSUE TITLE
Bug: Releases are not found

### ISSUE THREAD

**Issue by mboldysh** [VADOSWARE/pg_idkit#13]
# Bug

There are no releases present for this repo - https://github.com/VADOSWARE/pg_idkit/blob/main/releases so I can not download the library.

# Resolution Ideas

Add release binaries

**Comment by mboldysh** [comment]
Hi @t3hmrman! I just try to follow the instruction in `README` (Binary install section): 
> you may download (and verify the checksum of) a shared library versionfrom the [releases](https://github.com/VADOSWARE/pg_idkit/blob/main/releases)

but there are no releases when I click on this link.

My understanding is that I should download this shared library and put it to `/etc/postgresql/extensions`, isn't it?

**Comment by t3hmrman** [comment]
Ah @mboldysh apologies -- you have to build this library manually for now! There is a ticket to add a dockerfile #4 which will make it clearer, but if you look at [`pgx` instructions](https://github.com/tcdi/pgx) it is a bit more clear.

I'll improve the documentation soon and fix the install instructions!

**Comment by mboldysh** [comment]
Oh, got it, thanks. Now it's clear so I close this issue
