### ISSUE TITLE
Feature: Set up automated releases

### ISSUE THREAD

**Issue by t3hmrman** [VADOSWARE/pg_idkit#15]
# Context

Releases are not currently being produced

# Proposal

Add proper release production from CI via GH Actions.

- [ ] Release a rust crate with [`cargo-release`](https://github.com/crate-ci/cargo-release)
- [ ] Release the built `.so` & `.control` files as release artifacts
  - [ ] Support a matrix of:
    - [ ] arch (i.e. `amd64`, `arm64`/`aarch64`)
    - [ ] pg version (`pg10`,`pg11`,..,`pg16`)
    - [ ] libc (i.e. `glibc`, `musl`) (`musl` might not actually work for now...)
- [ ] Release to `pgxn` ([`pgxn-release-shell-action`](https://github.com/RekGRpth/pgxn-release-shell-action) or [`pgxn-action`](https://github.com/theory/pgxn-action))

# Alternatives

N/A

# Additional Links

N/A

**Comment by natanchagas** [comment]
@t3hmrman I've tried to fork the repository to help out with this, but you're using a custom image for the container which I don't have permission to use.

I was going to try out creating the release with this action: [Upload to Release Action](https://github.com/marketplace/actions/upload-to-release-action). Let me know if I can helpyou any further.

**Comment by t3hmrman** [comment]
Hey @natanchagas thanks for taking a look at this -- [the CI image](https://github.com/VADOSWARE/pg_idkit/blob/main/infra/docker/ci.Dockerfile) is the one you're referring to right?

It *should* be possible to build the CI image locally in your fork, but I think that workflow *is* somewhat painful like you noticed. To make it easier I need to publish the CI 

Since in addition to the docker container this ticket actually contains stuff for publishing the crate, I think it might be better if I handle this one... In addition to making the CI image available more easily (so you can use it from your fork)

**Comment by t3hmrman** [comment]
@natanchagas If you're still up for it, how do you feel about tackling https://github.com/VADOSWARE/pg_idkit/issues/8 ? 

It should be possible to make progress on that (and add an action for it, for example) *without* access to any other images

**Comment by t3hmrman** [comment]
Resolved by #53
