### ISSUE TITLE
Feature: support postgres 16.0

### ISSUE THREAD

**Issue by patrickmichalina** [VADOSWARE/pg_idkit#23]

**Comment by t3hmrman** [comment]
Thanks for the contribution @patrickmichalina -- any desire to take this on? Otherwise I'll try and get it done ASAP (and make some other changes I've been meaning to get to)

**Comment by t3hmrman** [comment]
A quick look upstream and [`pgrx` had some problems with PG16 in the past](https://github.com/pgcentralfoundation/pgrx/issues/1298). 

It *looks like* [it's solved as of `0.10.2`](https://github.com/rustprooflabs/pgfaker/pull/2)

**Comment by t3hmrman** [comment]
This should probably be done after #15 , so that people can pick which build they want to use (which should encapsulate the pg version)

**Comment by patrickmichalina** [comment]
Ok well I got it working here: https://github.com/patrickmichalina/pg_idkit/commit/5c060aa1b7f3c536dde3e1f89830b1f170897758

**Comment by t3hmrman** [comment]
If you'd like to contribute that code I'd love to have it!

A couple things:

- The feature addition is actually a [Rust SemVer minor change](https://doc.rust-lang.org/cargo/reference/semver.html#cargo-feature-add)
- This repo uses [Conventional Commits](https://www.conventionalcommits.org) so a commit with a message like `feat: add pgrx pg16 support` would be great
