### ISSUE TITLE
[Feature] please provide RPM package or release source code

### ISSUE THREAD

**Issue by vkingnew** [VADOSWARE/pg_idkit#29]
# Context

as so far i had not found any RPM package or source code package,it looks [pg_idkit] had not developed.

# Proposal

if there is RPM package it is very convenient to install and experience

**Comment by t3hmrman** [comment]
Hey @vkingnew thanks for this suggestion, sorry for the delay in getting to it!

I think before I can get an RPM build set up I need to start publishing proper artifacts/releases for `pg_idkit` -- definitely something I should get to soon, but this is probably blocked by https://github.com/VADOSWARE/pg_idkit/issues/15
