### ISSUE TITLE
current  RPM package version not support el8.

### ISSUE THREAD

**Issue by vkingnew** [VADOSWARE/pg_idkit#59]
$ cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.9 (Ootpa)
$ rpm -ivh pg_idkit-0.2.1-pg16.x86_64.rpm 
error: Failed dependencies:
	libc.so.6(GLIBC_2.33)(64bit) is needed by pg_idkit-0:0.2.1-pg16.x86_64
	libc.so.6(GLIBC_2.34)(64bit) is needed by pg_idkit-0:0.2.1-pg16.x86_64
please support rhel8,rhel9.

**Comment by t3hmrman** [comment]
Hey @vkingnew thanks for the report! 

It looks [RHEL8 does not support newer versions of glibc](https://access.redhat.com/discussions/7026438). 

Please consider either:
- Building the software from source on RHEL8 (it's a Rust project)
- Upgrading to RHEL9

If you'd like to contribute RHEL8 support I'd be happy to have the contribution.
