### ISSUE TITLE
Feature: add arm64 images

### ISSUE THREAD

**Issue by geekodour** [VADOSWARE/pg_idkit#67]
would like to run it on my arm machine, seems like docker images and the releases are built for amd. can send a pr for it? but wanted to know if there are any limitations.

**Comment by t3hmrman** [comment]
Hey @geekodour thanks for taking a look! Yeah I think we could definitely support AMD machines, I'd welcome a PR!

Postgres runs on ARM and Rust builds for ARM of course, and [`pgrx` seems to support building on ARM](https://github.com/pgcentralfoundation/pgrx/blob/7ea24807bd5382f74cf5b4ea547452bca37203ee/docs/src/extension/build/cross-compile.md#where-to-get-the-headers). Thanks for taking a look at this, I'd be happy to review a PR when you have one!

**Comment by t3hmrman** [comment]
Hey this isn't done, but noting that we actually [already have an issue for this](https://github.com/VADOSWARE/pg_idkit/issues/30) -- will close this in favor of that!
